version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: scis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: src/SCIS.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=scis_db;Username=postgres;Password=password
      - Jwt__Key=SCIS_Super_Secret_Key_For_JWT_Token_Generation_2024
      - Jwt__Issuer=SCIS.API
      - Jwt__Audience=SCIS.Users
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:5000/api
    depends_on:
      - api

volumes:
  postgres_data:
